/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#3a485c",
        "secondary-fixed-dim": "#c8c6c3",
        "secondary": "#5e5e5c",
        "on-tertiary-container": "#374559",
        "surface-bright": "#fbf9f9",
        "on-surface-variant": "#534434",
        "on-secondary-container": "#636360",
        "inverse-on-surface": "#f2f0f0",
        "on-tertiary-fixed": "#0d1c2f",
        "divider": "#E5E1DA",
        "surface-container-highest": "#e4e2e2",
        "hazard-smoke": "#475569",
        "outline-variant": "#d8c3ad",
        "primary-fixed-dim": "#ffb95f",
        "surface": "#fbf9f9",
        "surface-elevated": "#FFFFFF",
        "hazard-water": "#2563EB",
        "tertiary": "#515f74",
        "secondary-container": "#e1dfdc",
        "surface-container-low": "#f5f3f3",
        "primary": "#855300",
        "tertiary-fixed-dim": "#b9c7e0",
        "primary-container": "#f59e0b",
        "inverse-surface": "#303031",
        "background": "#fbf9f9",
        "surface-container": "#efeded",
        "inverse-primary": "#ffb95f",
        "on-primary-container": "#613b00",
        "surface-dim": "#dbdada",
        "on-error": "#ffffff",
        "tertiary-fixed": "#d5e3fd",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "outline": "#867461",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#474744",
        "on-background": "#1b1c1c",
        "secondary-fixed": "#e4e2de",
        "on-secondary-fixed": "#1b1c1a",
        "tertiary-container": "#a3b2ca",
        "hazard-fire": "#E11D48",
        "on-primary-fixed-variant": "#653e00",
        "surface-tint": "#855300",
        "error": "#ba1a1a",
        "surface-variant": "#e4e2e2",
        "on-surface": "#1b1c1c",
        "on-error-container": "#93000a",
        "surface-container-high": "#e9e8e8",
        "on-primary-fixed": "#2a1700",
        "primary-fixed": "#ffddb8"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin": "24px",
        "gutter": "16px",
        "unit": "4px",
        "container-max": "1920px"
      },
      fontFamily: {
        "data-mono": ["JetBrains Mono", "monospace"],
        "body-base": ["Geist", "Inter", "sans-serif"],
        "label-xs": ["JetBrains Mono", "monospace"],
        "display-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "body-sm": ["Geist", "sans-serif"],
        "data-lg": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "data-mono": ["13px", { "lineHeight": "16px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-base": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "label-xs": ["11px", { "lineHeight": "12px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "display-lg": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-sm": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
        "data-lg": ["18px", { "lineHeight": "24px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
